
name: Test Code FreeBSD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          release: "14.1"
          prepare: |
            pkg install -y go

          # -x - to print all executed commands
          # -e - to faile on first error
          run: |
            set -e -x
# FIXME: revert
            time go test -timeout 1m -failfast -tags unit,component,integration ./client/internal/routemanager/systemops/...

